config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get "components", to: "pages#components"
  get "ui-kit", to: 'pages#ui'
  get "/skills", to: "skills#index"
  get "/steptwo", to: "pages#steptwo", as: :steptwo
  get "dashboard", to: "pages#dashboard"

  get "/confirm", to: "jobs#confirm", as: :confirm
  # get "skills/:id", to: "skills#show"
  resources :skills, only: [:index, :show] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]

  get "dashboard/skills", to: "pages#dashboardmyskills"
  get "dashboard/jobs", to: "pages#dashboardmyjobs"
  resources :skills, only: [:index, :show]

  resources :jobs, only: [:index, :show]
  get "/user_edit", to: "pages#user_update"

  # get "skills/:id", to: "skills#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :job_skills
  has_many :skills, through: :job_skills
end

app/models/job_skill.rb
class JobSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :job
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :job_skills
  has_many :jobs, through: :job_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites


end

app/models/user_job.rb
class UserJob < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :full_name, :student, :skills, :interests, :developer, :interests])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :full_name, :student, :interests])
  end

  def after_sign_up_path_for(resource)
    jobs_path # Or :prefix_to_your_route
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.new
    @skill = Skill.find(params[:skill_id])
    @favorite.skill = @skill
    @favorite.user = current_user
    @favorite.save!

    redirect_to skill_path(@skill)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @skill = @favorite.skill
    @favorite.destroy
    redirect_to skill_path(@skill)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    # JobMailer.job_sent.deliver_later
    if params[:query].present?
      @jobs = []
      skill = Skill.find_by(name: params[:query].upcase )
      Job.all.each {|job| @jobs << job if job.skills.include?(skill)}
    else
      @jobs = Job.all
    end
  end

  def confirm
    JobMailer.job_sent(current_user).deliver_later
    redirect_to jobs_path
  end
end

app/controllers/pages_controller.rb
require 'date'
class PagesController < ApplicationController
  def home

  end

  def components
  end

  def ui
  end

  def index
  end

  def steptwo

  end

  def dashboard

  end


  def user_update
    @user = current_user
    interests = ["Front-End", "Back-End", "Full-Stack"]
    skills = ["Ruby", "HTML", "CSS", "JavaScript", "Python", "Rails"]
    developer = params["snippet"]["archived"] == "1"
    skills = skills.select { |skill| params.key?(skill) }
    interests = interests.select { |interest| params.key?(interest) }
    skills << params[:query] unless params[:query] == ""
    @user.update!(skills: skills,
      interests: interests,
      developer: developer,
      form_completed: params[:form_completed] == "true")
      redirect_to jobs_path
  end

  def dashboardmyskills
    @favorites = current_user.favorites
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :username, :student, :skills, :developer, :form_completed, interests: [])
  end



  def dashboardmyjobs
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    :skills
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def show
    @skill = Skill.find(params[:id])
    @resources = []
    @skill.resources.each do |r|
    @resources << eval(r)
    end

    @beginner_resources = @resources.select { |res_hash| res_hash[:difficulties] == 'beginner' }
    @intermediate_resources = @resources.select { |res_hash| res_hash[:difficulties] == 'intermediate' }
    @advanced_resources = @resources.select { |res_hash| res_hash[:difficulties] == 'advanced' }
  end

  def index
    if current_user
      if !current_user.student && !current_user.form_completed
        redirect_to steptwo_path
      end
    end

    @skills = Skill.all
    if params[:query].present?
      if params[:query] == "frontend"
        @skills = Skill.where(frontend: true)
      end

      if params[:query] == "backend"
        @skills = Skill.where(backend: true)
      end

      if params[:query] == "all"
        @skills = Skill.all
      end

    end
  end
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  protected

  def after_sign_up_path_for(resource)
    redirect_to steptwo_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_job_banner.html.erb
<div class="job-banner">
  <div class="banner-text">
    <h1>Programming </h1>
    <p>Find the job offers that suit your programming skill</p>
    <i class="fa-brands fa-css3"></i>
    <i class="fa-brands fa-js"></i>
    <i class="fa-brands fa-html5"></i>
    <i class="fa-brands fa-python"></i>
    <i class="fa-brands fa-php"></i>
    <i class="fa-brands fa-java"></i>
    <i class="fa-brands fa-r-project"></i>
    <i class="fa-brands fa-golang"></i>
  </div>

</div>

app/views/jobs/index.html.erb
<%#= render 'job_banner' %>
<div class="job-modal" style="display: none;">
</div>

<div class="apply-modal">
</div>

<% if user_signed_in? %>
  <div class="signed-in"></div>
<% end %>

<div class="job-cards">

  <div class="job-searchbar">
    <%= form_tag jobs_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control job-search-fill",
        placeholder: "Type your programming skill e.g. ruby"
      %>
      <%= submit_tag "Search", class: "button-primary" %>
    <% end %>
  </div>

  <div class="row">
    <% @jobs.each do |job| %>
      <div class="col-lg-3 col-md-6 mb-5">
        <%#= link_to job_path(id: Job.find_by(params[:id])) do %>
          <div class="job-card">
            <p class="job-description"><%= job.description %></p>
            <div class="job-top">
              <h3> <%= job.title %> </h3>
              <i class="fa-regular fa-building d-line mt-3"></i>
              <p> <%= job.company %></p>
            </div>
            <hr>
            <div class="job-bottom">
              <% job.skills.each do |skill| %>
                <%= skill.name %>
              <% end %>
            </div>
          </div>
        <%# end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proskills</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.ico"%>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if !current_page?("/steptwo") %>
    <%= render 'shared/navbar' %>
    <% end %>
    <div style="height:96.37px;"></div>
    <%= yield %>
    <% if !current_page?("/steptwo") %>
    <%= render 'shared/footer' %>
    <% end %>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/_dashboard_banner.html.erb
<div class="job-banner">
  <div class="banner-text">
    <h1 class="welcome">Hey <%= current_user.username %></h1>
    <i class="fa-brands fa-css3"></i>
    <i class="fa-brands fa-js"></i>
    <i class="fa-brands fa-html5"></i>
    <i class="fa-brands fa-python"></i>
    <i class="fa-brands fa-php"></i>
    <i class="fa-brands fa-java"></i>
    <i class="fa-brands fa-r-project"></i>
    <i class="fa-brands fa-golang"></i>
  </div>
</div>

app/views/pages/_sidebar_skills.html.erb
<div class="sidebar">
  <h1 class="welcome">Hey <%= current_user.username %></h1>
  <span> <strong><%= link_to "My skills", dashboard_skills_path, class:"button-primary" %></strong> </span>
  <span><%= link_to "My jobs", dashboard_jobs_path, class:"button-primary" %></span>
</div>

app/views/pages/components.html.erb
<%= render 'components/job_banner' %>
#cards
<div class="container">
<%= render 'components/job_card' %>
</div>
#footer

app/views/pages/dashboardmyjobs.html.erb
<main class="dashboard-page">
  <div class="dashboard row">
    <div class="dash-left col-4">
    <%= link_to "My skills", dashboard_skills_path, class:"button-primary button-primary-small" %>
    <%= link_to "My jobs", dashboard_jobs_path, class:" button-primary button-primary-small"%>
    </div>
    <div class="dash-right col-8">
      <div class="dash-card">
      </div>
    </div>
  </div>
</main>

app/views/pages/dashboardmyskills.html.erb
<main class="dashboard-page">
  <%= render "dashboard_banner" %>
  </div>
  <div class="container dash-wrapper">
    <div class="dash-profile col-4">
      <%= image_tag "profile_picture.png", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown" %>
      <h3><%= current_user.full_name %></h3>
      <%= Date.today %>
      <hr>
      <h5 class="header">My Interests</h5>
        <% current_user.interests.each do |interest| %>
      <p class="dash-content"><%= interest %></p>
      <% end %>
      <hr>
      <h5 class="header">My Skills</h5>
      <%current_user.skills. each do|skill| %>
        <p class="dash-content"><%= skill %></p>
      <% end %>
    </div>
    <div class="dashboard col-8">
      <div class="dash-nav">
       <h1><%= "Favorite Skills"%></h1>
      </div>
      <div class="dash-right" style="padding-top: 40px;margin-left: 30px;">
        <div class="row w-100 justify-content-around">
          <% @favorites.each do |favorite| %>
            <%= link_to skill_path(id: favorite.skill.id), class:"col-3" do %>
              <div class="card-small">
                <div style="background-color: <%= favorite.skill.color %>; color: white; display: flex; align-items: center; justify-content: center; border-radius: 5px;">
                  <% if favorite.skill.name == "C++" %>
                    <%= image_tag "skill_logos/c.svg" %>
                  <% else %>
                    <%= image_tag "skill_logos/#{favorite.skill.name.downcase}.svg" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>
  </div>
  </div>
</main>

app/views/pages/home.html.erb
<main class="row m-0 landing-page">

  <div class="home-left col-lg-4 col-md-4 col-sm-12">
    <h1>Proskills.</h1>
    <p>Would you like to learn programming skills or seek programming jobs that fit your skills?</p>
    <% if current_user %>
    <h3><%= link_to "Explore", skills_path, class:"button-primary"%></h3>
    <% else %>
    <h3><%=link_to "Sign up", new_user_registration_path, class:"button-primary"%></h3>
    <% end %>
  </div>

  <div class="home-right col-lg-8 col-md-8 col-sm-12">

    <%= link_to skills_path do %>
      <div class="student">
        <%= image_tag "landing/student.png", class:"student-img" %>
        <div class="quote quote-student">
          <p>"I want to learn programming"</p>
        </div>
      </div>
    <% end %>

    <%= link_to jobs_path do %>
      <div class="jobseeker">
        <%= image_tag "landing/jobseeker.png"%>
        <div class="quote quote-jobseeker">
          <p>"I want to find a programming job"</p>
        </div>
      </div>
    <% end %>
  </div>

</main>

app/views/pages/stepone.html.erb
<div class="container">
  <div class="cards">
    <div class="card-student">
      <p>Enter as a student</p>
      <%= link_to "Explore", "skills#index", class:"button-primary button-primary-small" %>
    </div>
    <div class ="card-job">
      <p>You want to find a job?</p>
      <p><%= link_to "Continue", "jobs#index", class:"button-primary button-primary-small" %></p>
    </div>
  </div>
</div>

app/views/pages/steptwo.html.erb
<div class="container steptwo ">
  <div class="form form-2">
    <h2 class="header-form">Give us some more Information</h2>
    <form action="/user_edit">

    <hr>

      <label class="input" ><h4>What programming skills do you have?</h4></label>
      <div class="checkboxes-skill row w-75 m-auto" >
        <div class="tag-item col-4">
          <input class="tag-selector" type="checkbox" id="Ruby" name="Ruby">
          <label style="width: 100%" for="Ruby">Ruby</label>
        </div>

        <div class="tag-item col-4">
          <input class="tag-selector" type="checkbox" id="HTML" name="HTML">
          <label style="width: 100%" for="HTML">HTML</label>
        </div>

        <div class="tag_item col-4">
          <input class="tag-selector" type="checkbox" id="CSS" name="CSS">
          <label style="width: 100%" for="CSS">CSS</label>
        </div>

        <div class="tag_item col-4">
          <input class="tag-selector" type="checkbox" id="JavaScript" name="JavaScript">
          <label style="width: 100%" for="JavaScript">JavaScript</label>
        </div>

        <div class="tag-item col-4">
          <input class="tag-selector" type="checkbox" id="Python" name="Python">
          <label style="width: 100%" for="Python">Python</label>
        </div>

        <div class="tag-item col-4">
          <input class="tag-selector" type="checkbox" id="Rails" name="Rails">
          <label style="width: 100%" for="Rails">Rails</label>
        </div>
      </div>

      <div class="others">
        <label>Others?</label>
        <input type="input" class="input1" name="query">
      </div>

        <hr>

      <div>
        <label class="input2" ><h4>What are your interests?</h4></label>
      </div>

      <div class="checkbox-job row w-75 m-auto">
        <div class="tag-item col-4">
          <input class="tag-selector" type="checkbox" id="Front-End" name="Front-End">
          <label style="width: 100%;" for="Front-End">Front-End</label>
        </div>

        <div clas="tag-item col-4" style="width: auto;">
          <input class="tag-selector" type="checkbox" id="Back-End" name="Back-End">
          <label style="width: 100%;" for="Back-End">Back-End</label>
        </div>

        <div class="tag-item col-4">
          <input class="tag-selector" type="checkbox" id="Full-Stack" name="Full-Stack">
          <label style="width: 100%; " for="Full-Stack">Full-Stack</label>
        </div>
      </div>

      <hr>

      <div>
        <label class="input3" ><h4>Did you already work as a developer?</h4></label>
        <fieldset class="form-group boolean optional snippet_archived">
          <div class="form-check">
            <input name="snippet[archived]" type="hidden" value="0">
            <input class="form-check-input boolean optional toggle" type="checkbox" value="1" name="snippet[archived]" id="snippet_archived">
            <label class="form-check-label boolean optional" for="snippet_archived">Yes</label>
          </div>
        </fieldset>
        <%# <input type="checkbox" class="toggle">
        <label for="developer">Yes</label> %>
      </div>
      <input type="hidden" id="form_completed" name="form_completed" value="true">

      <input type="submit" name="Submit" class="button-primary mt-4 mb-0" value="Submit">

    </form>
  </div>
</div>

app/views/pages/ui.html.erb
<div class="container">
  <h2>Buttons</h2>
  <h3><%=link_to "Join us", "pages#home", class:"button-primary"%></h3>
  <div class="card-student">
    <p>You want to learn programming languages?</p>
    <%= link_to "Explore", "skills#index", class:"button-primary button-primary-small" %>
  </div>
  <div class ="card-job">
    <p>You want to find a job?</p>
    <p><%= link_to "Find job", "jobs#index", class:"button-primary button-primary-small" %></p>
  </div>
  <h2>banner</h2>
  <%= render "shared/banner" %>
</div>

app/views/shared/_banner.html.erb
<div class="container">
  <h2>See the variety of coding</h2>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-flex">

    <div class="footer-left">
      <h1>Proskills.</h1>
      <p>Learn programming skills or seek programming jobs?</p>
      <p>We are here for you.</p>
    </div>

    <div class="footer-right">
      <div class="help">
        <ul>
        <li class="footer-title">Help</li>
        <li><a href="#">Contact us</a></li>
        <li><a href="#">FAQ</a></li>
        </ul>
      </div>

      <div class="follow">
        <ul>
        <li class="footer-title">Follow us</li>
        <li><a href="#">Instagram</a></li>
        <li><a href="#">Facebook</a></li>
        </ul>
      </div>
    </div>

  </div>

  <p class="company-symbol">© 2022 Proskills</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1>Proskills.</h1>
  <% end %>

  <div class="navbar-right">
    <ul class="navbar-nav">
        <li><%= link_to "Learning skills", skills_path, class: "nav-link" %></li>
        <li><%= link_to "Seeking jobs", jobs_path, class: "nav-link" %></li>
      <% if user_signed_in? %>
        <li class="dropdown">
          <%= image_tag "profile_picture.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My skills", dashboard_skills_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path, class:"button-sign-up" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_signup-form.html.erb
<h2>Weekly Coding Challenge #1: Sign in/up Form</h2>
<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form action="#">
			<h1>Create Account</h1>
			<div class="social-container">
				<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
				<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
			</div>
			<span>or use your email for registration</span>
			<input type="text" placeholder="Name" />
			<input type="email" placeholder="Email" />
			<input type="password" placeholder="Password" />
			<button>Sign Up</button>
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form action="#">
			<h1>Sign in</h1>
			<div class="social-container">
				<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
				<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
			</div>
			<span>or use your account</span>
			<input type="email" placeholder="Email" />
			<input type="password" placeholder="Password" />
			<a href="#">Forgot your password?</a>
			<button>Sign In</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Hello, Friend!</h1>
				<p>Enter your personal details and start journey with us</p>
				<button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>

<footer>
	<p>
		Created with <i class="fa fa-heart"></i> by
		<a target="_blank" href="https://florin-pop.com">Florin Pop</a>
		- Read how I created this and how you can join the challenge
		<a target="_blank" href="https://www.florin-pop.com/blog/2019/03/double-slider-sign-in-up-form/">here</a>.
	</p>
</footer>

app/views/skills/_skill_banner.html.erb
<div class="job-banner">
  <div class="banner-text">
    <h1 class="welcome">Programming Skills</h1>
    <i class="fa-brands fa-css3"></i>
    <i class="fa-brands fa-js"></i>
    <i class="fa-brands fa-html5"></i>
    <i class="fa-brands fa-python"></i>
    <i class="fa-brands fa-php"></i>
    <i class="fa-brands fa-java"></i>
    <i class="fa-brands fa-r-project"></i>
    <i class="fa-brands fa-golang"></i>
  </div>
</div>

app/views/skills/index.html.erb
<%= render "skill_banner" %>
<div class="text-center m-5">
  <%= link_to "Front end", skills_path(query: "frontend"), class: "button-primary"%>
  <%= link_to "Back end", skills_path(query: "backend"), class: "button-primary" %>
  <%= link_to "All", skills_path(query: "all"), class: "button-primary" %>
</div>
<div class="container">
  <div class="row">
    <% @skills.each do |skill| %>
      <%= link_to skill_path(id: skill.id), class: "skills-cards-link col-lg-3 col-md-4 col-sm-6" do %>
        <div class="card">
          <div class="imgbx">
            <div class="mytext" style="height: 100%; width: 100%; background-color: <%= skill.color %>; color: white; display: flex; align-items: center; justify-content: center;">
              <% if skill.name == "C++" %>
                <%= image_tag "skill_logos/c.svg" %>
              <% else %>
                <%= image_tag "skill_logos/#{skill.name.downcase}.svg" %>
              <% end %>
            </div>
          </div>
          <div class="contentbx">
            <div class="content">
              <p><%= skill.name %>!</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/skills/show.html.erb
<main class="show-page">

  <div class="skill-top row">

    <div class="language-card col-lg-6 col-md-12 pe-5">
      <div class="language-title">
        <div class="d-flex">
          <%= image_tag "skill_logos/#{@skill.name == "C++" ? "c" : @skill.name.downcase}.svg", class:"skill-logo me-2" %>
          <h1> <%= @skill.name %> </h1>
        </div>
      <% if user_signed_in? %>
        <% if !Favorite.find_by(user_id: current_user.id, skill_id: @skill.id) %>
          <%= link_to skill_favorites_path(@skill.id), method: :post, remote: true, data: {favorites_target: "like", action: "click=>favorites#like"} do  %>
            <i class="fa-regular fa-heart fa-xl" ></i>
          <% end %>
        <% else %>
          <%= link_to favorite_path(Favorite.find_by(user_id: current_user.id, skill_id: @skill.id)), method: :delete, remote: true, data: {favorites_target: "like"} do %>
            <i class="fa-solid fa-heart fa-xl"></i>
          <% end %>
        <% end %>
      <% else %>
        <i></i>
      <% end %>
      </div>

      <p><%= @skill.description %></p>

      <p class="why-like-title">Why do we like it?</p>
      <ul>
        <% @skill.bulletpoints.each do |point| %>
          <li> <%=point %> </li>
        <% end %>
      </ul>
    </div>

    <div class="language-complier col-lg-6 col-md-12">
      <iframe frameborder="0" width="100%" height="500px" src="https://replit.com/@Joy333/<%= @skill.name == "C++" ? "c" : @skill.name.downcase %>?lite=true"></iframe>
    </div>
  </div>

<%# <div class="row"> %>
  <%# <div class="col-3"></div> %>
  <div class="skill-bottom">
    <div class="skill-person">
      <%= image_tag "skill_sitting.svg" %>
      <div class="quote">
        <p>"Want to learn <%= @skill.name %>? We have learning resources for you!"</p>
      </div>
    </div>
    <% if current_user == nil %>
      <div class="see-resources-alert">
        <p>Would like to see the learning resources?</p>
        <%= link_to "Sign up", new_user_registration_path, class:"button-sign-up" %>
        <p> or </p>
        <%= link_to "Log in", new_user_session_path, class:"button-sign-up" %>
      </div>
    <% end %>

    <div class="resources", style="background-image: url(<%= image_path('resources_background.png')%>);">

      <div class=" <%= current_user ? "" : "blur" %> resources-cards resources-card1">
        <h3>Beginner</h3>
        <ul>
          <% @beginner_resources.each do |br| %>
            <li> <%= link_to br[:name], br[:link], target: :_blank %> </li>
          <%end%>
        </ul>
      </div>


      <div class="<%= current_user ? "" : "blur" %> resources-cards resources-card2">
        <h3>Intermediate</h3>
        <ul>
          <% @intermediate_resources.each do |br| %>
            <li> <%= link_to br[:name], br[:link], target: :_blank %> </li>
          <%end%>
        </ul>
      </div>
      <div class=" <%= current_user ? "" : "blur" %> resources-cards resources-card3">
        <h3>Advanced</h3>
        <ul>
          <% @advanced_resources.each do |br| %>
            <li> <%= link_to br[:name], br[:link], target: :_blank %> </li>
          <%end%>
        </ul>
      </div>
    </div>

  </div>
  <%# <div class="col-3"></div> %>
<%# </div> %>
</main>